#+TITLE: Manuscript (pre-Latex)
If I were given the choice to remember a week of my life down to the finest sensory details, I would, without a doubt, use it to remember the experiences i had on my family's trip to the Black Hills.
While the vacation itself was immensely fun, the way there left a lot to be desired.  As a family, we didn't really talk to each other in the car much, and often resorted to doing whatever it was that we usually did in the car, with my dad driving, my mom reading, my brother watching videos and myself listening to music.  When I listen to music on long car rides, I usually look out the window at passing scenery;  I'm always on the right side so my vision isn't obscured by cars passing in another lane (except on roads with four or more lanes, of course).  However, on this ride, the scenery left something to be desired.  There were about as many hills as there are cats at the north pole, and the expanse was about as much of a feast for the eyes as plain tofu is for the mouth.  60% of the time, the sky would converge at the horizon with rows of crops.  For the most part, I wasn't bothered by it, as this scene was just a sort of moving backdrop behind my thoughts.  Listening to music and letting my mind wander is my war tactic against boredom when sitting through long car rides.
When we neared our destination, being just shy of twenty minutes away from it, we stopped at a place my dad had been wanting to try since planning this trip.  The food came much appreciated, as I'd been tired of subsisting off of junk food for the past few hours, though one could argue that the pizza was just as bad for me, if not worse.  The decor in the joint was rather dry.  The best way I could really describe such a place would be as the abandoned child of a bathroom, a pub, and a gymnasium, and I'll leave that as something for the imagination to chew on.  There was a steep disparity between the ambience and the quality of our food, though.  The pizza we got was warm, flavorful and had a marvelous composition.  It didn't leave 16 inches of thin cheese strings between your chin and the plate when you tried your hardest to take a bite from it.  The pepperonis came clean off likewise.  Had I not jumped the gun and subjected my mouth to Hell Junior by taking a bite far too soon, it would've been perfect.  Maybe that's what people refer to as user error, though.
