#+TITLE: Manuscript (pre-Latex)
If I were given the choice to remember a week of my life down to the finest sensory details, I would, without a doubt, use it to remember the experiences i had on my family's trip to the Black Hills.
While the vacation itself was immensely fun, the way there left a lot to be desired.  As a family, we didn't really talk to each other in the car much, and often resorted to doing whatever it was that we usually did in the car, with my dad driving, my mom reading, my brother watching videos and myself listening to music.  When I listen to music on long car rides, I usually look out the window at passing scenery;  I'm always on the right side so my vision isn't obscured by cars passing in another lane (except on roads with four or more lanes, of course).  However, on this ride, the scenery left something to be desired.  There were about as many hills as there are cats at the north pole, and the expanse was about as much of a feast for the eyes as plain tofu is for the mouth.  60% of the time, the sky would converge at the horizon with farmland.
