#+TITLE: Brainstorming strategy 2:  rush write list
- I'm going to talk about my trip to South Dakota
- We went to the black hills
- I don't know what to write
- I remember going out into a hot tub a few nights
- We stayed up in the mountains 
- I kinda remember it being slightly more hard to breathe up there
- There were a lot of Christian living-centered books in the house we stayed in.
- The house felt very much like a home I might live in myself, it was well-decorated
- There was a large cliff-like drop behind our house, so our parents told us to stay safe
- I remember the air feeling really, really pleasant
- However, it was also very dry air
= When it rained the air left afterwards really felt nice on my skin
- I remember panning for gold once, though I found none.  It was still a fun experience
- i had a lot of fun on that trip
- We went to see Mt. Rushmore.  It was cool
- I got a small rose-gold coin there with an engraving of Mt. Rushmore on there as well.
- I enjoyed hiking along the trail around Mt. Rushmore.
- There was a lot of hiking we did in the Black Hills.  The terrains of places we visited was very diverse.
- I remembered going to the badlands.  It looked like a martian landscape.
- Everywhere you looked, it looked very extraterrestrial, like you'd taken a futuristic vacation
- We sat in the back of our car eating Pringles for a while, before leaving to go hiking.
- I remember scrambling up a hill, carefully placing my feet in footholds scattered along there
- There were not a lot of animals there
- The layers of clay and sediment were like a layer cake.  Very surreal
- Reminded me of a Salvador Dali painting.
- I also remember going along a drive in a state park.  We saw animals like deer and buffalo, though not in surplus
- I remember seeing a few deer around the outside of the house we stayed at.
- I liked the car ride up there
- Car rides make me happy a lot
- I can listen to music and look out the window and think
- The terrain on the way there and back was flat and extended in such a manner to the horizon
- It wasn't intereesting but I could think a lot wihile having something to look at 
- Music makes me very happy and I listen to it a lot.  I listen to a lot of electronic music
- I think its cool
- The fog that settled on the area some mornings entertained me
- the house we were in was sort of situated on a plateau on the top of a mountain
- maybe it was just my mind but i think i had to get somewhat acclimated to the thinner air at the top (though we weren't really that high i think)
- the room i stayed in was really cool and cozy
- the bed felt comfortable enough
- though being remote as it was, the house felt rather silent
- the suburban noise around my actual house is usually a comforting element to me, despite sometimes waking me up
- the silence here, though, was rather oppressive
- i would usually put headphones in at night to reason with it, as my mind could then better accept it
- im listening to relaxedcreeper right now n he has really cool sounds i think
- thats unrelated to the writing but i think i just need to keep talking
- so when i was in my room one night (like around the fifth day) i heard a sound that sort of resembled stone or sand crumbling in a wall
- it kind of freaked me out but i brushed it off and went back to whatever i was doing on my phone at the time
- but i kept hearing it, and it went on for about 5 minutes before i went to go investigate it
- i went to go to the wall where it was coming from, tapped the wall.  i immediately met another one of those crumbling/scratching sounds
- then i realized it really was more of a scratching sound
- it was a mouse
- there was a mouse in the wall
- i hate mice
- i hate basically anything that can land on/crawl on me against my will
- so i basically absolutely despise bugs and non-pet rodents
- hmmm i jsut realised i used "basicallY" i read that that was a crutch word at one point and its not good to use in your writing
- i think i agree that it's probably a bad idea to do so but sometimes it's a word you can use to keep on talking and fill the silence
- thats sorta what you need to do to rush write, right?  so that makes sense that i'd use it here
- i guess i'll ignore it for now
- i don't know if i've run out of topics to talk about for now
- oh, oh right, i was gonna write about this earlier:  my nightmare of a car ride that we took about halfway through the trip
- we were riding around some mountainous terrain in a national park and we came to the base of the hill
- a hill, i mean.  so bassically there was a winding trail that climbed around it.  at a glance it looked pretty perilous
- how it looked in NO way entailed how it actually felt.  there were no guard rails, and it was about as wide as 80% of your typical residential street
- i don't know why it felt particularly scary except for the constant fear of falling off the side running through my mind
- going up was easily the hardest part to come to terms with for my mind considering we were driving on the right (and unguarded) side of the road
- this was at a time where i really hadn't come to terms with the idea of death and its finality, i was still having a lot of trouble with it at the time
- i dont know if i have enough ideas right now
- when we went up there, it was kind of impressive.  you could see a large portion of the park we were visiting.  greenery for miles, exposed rock faces.
- at the top there was a sort of stone brick structure.  the bricks looked weathered and had a yellow tint to the best of my memory.  the wind was not too strong so i felt pretty safe up there
- i remember one more thing about this, the fact that my parents were against me wearing headphones or listening to music while we were driving through the park
- i dont really blame them for wanting a stronger sense of family when we were on a family vacation but it did nothing to ease my anxiety while traversing that path up the hill.
- it really felt like one of the slowest climbs of my life, i was just hoping that the next circle around the small mountain would be our last before we arrived

